[[tblis]]
arch = "x86_64"
git-tree-sha1 = "bad39b751ed9b819c0e04ac492bb388e5b494858"
os = "macos"

    [[tblis.download]]
    sha256 = "7c2e882d7c2fccb049d3bc301745a3792594fa171f6796628267ecec9b31735c"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-apple-darwin.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68843265f1376289359e93f4dc05e88ffb48087c"
libc = "glibc"
os = "linux"

    [[tblis.download]]
    sha256 = "c15a36dcb136ab1755e127f5c681b177d738475e249832346b3312c77413cc4b"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cd26ea022b106e1b653c0278a3e1a5d08f96ab7"
libc = "glibc"
os = "linux"

    [[tblis.download]]
    sha256 = "31074c180e8f3e5d0f2c2e562b1d2dce60f5413793581072752ceab5874b2e47"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d33332d00d3b393df984cd81d252dc2be2a725b2"
libc = "musl"
os = "linux"

    [[tblis.download]]
    sha256 = "06c5f10d2380b10f05374799b0f9a45ee131cd0eb6550fa9d2f27bf8ee4e10cd"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[tblis]]
arch = "x86_64"
git-tree-sha1 = "0d1555d05be29424ece47eb3c8a8e3edc5b1a76e"
os = "freebsd"

    [[tblis.download]]
    sha256 = "b24082f7005909d49fcb758043d0418031af3243ec460d77b9916c354f32945f"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "651d14608cdbf2d341036db97b04097c8e8229d7"
os = "windows"

    [[tblis.download]]
    sha256 = "2d76ca08f4cce3b2b3a0cdbb56bcd05b2ae724e869cdfd5e50538bfcb2cd7b9c"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f07118527b36952629ea411bdd8e336cb0d0eca"
os = "windows"

    [[tblis.download]]
    sha256 = "57ff6044038c5b3bcd8d271f25c2efcf5e3ec8c99063993ac0d32dd047022bfb"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+3/tblis.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
