[[tblis]]
arch = "x86_64"
git-tree-sha1 = "90988f7fe668f7692137684cff3dbaa6aef33228"
os = "macos"

    [[tblis.download]]
    sha256 = "27e690cdcf86c6c6a63e817a1a3fcdb2d6971c865a0b5b8bf93b0f45244e066f"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-apple-darwin.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab65bf2240f1d4ddaec501ae9f0e7389eaff60c2"
libc = "glibc"
os = "linux"

    [[tblis.download]]
    sha256 = "0f288b5fd636bb324997d3846d824af75680e6594a9db7387af882f1b93928ad"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d87a4de4dd45bff1a5a45f33f83fc152657662e"
libc = "glibc"
os = "linux"

    [[tblis.download]]
    sha256 = "f57ea5851f3c58d3da5e6d0c494b953fc5caff8cd8b2056ce3989ca67e8c660e"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f6785e1dfe181cf23f054d1193b3e7f0186c6f0"
libc = "musl"
os = "linux"

    [[tblis.download]]
    sha256 = "25850ab7ff30c31548f5efe21991c429660bc4199bb01483fa9ff7d81d98d1ac"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[tblis]]
arch = "x86_64"
git-tree-sha1 = "ad703eb5f0769167091f1f435db8c99d75e826b2"
os = "freebsd"

    [[tblis.download]]
    sha256 = "d252ae78ca47c272efc2d2d03dc6bba276459e8f8a91f34e407e0409dee9b37b"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3914c3cd831f8f620060a218c453c4330ce984e3"
os = "windows"

    [[tblis.download]]
    sha256 = "03cef496d270f6dbba2f81528b57a4fb2ee59acf1bf01e5c0626cb2b3f6f0134"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408d9e7bcc826e28b8f4e79131a3bd6dad09d06f"
os = "windows"

    [[tblis.download]]
    sha256 = "74d7fb4599ead573d6aaddbc3de85c8362a641bdb8651c9054fef8bf4e3f02b6"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+2/tblis.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
