[[tblis]]
arch = "x86_64"
git-tree-sha1 = "0482ca519f2ba03b34848d484fd38fb0708fe7d1"
os = "macos"

    [[tblis.download]]
    sha256 = "0439675ef06414f915e783e15a19e724ab1c3c50ac246547be5f96c7ca527633"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-apple-darwin.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efa2ccb468d7e96a947ef8a79b0f4b6a2222e7b8"
libc = "glibc"
os = "linux"

    [[tblis.download]]
    sha256 = "04a959dd519ce2fc7c84c2014189e740ff9eecdf21f88dcb17a64bbbaf483918"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88acd4122206bc00423af187fad99a0fb01f433e"
libc = "glibc"
os = "linux"

    [[tblis.download]]
    sha256 = "1d13c2f35cf9ea02d171a44ae991f189b639b666cc6f03fc03bf708234dc23ec"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08cb045ab2344c4830f5dde4584c456ffcd45d77"
libc = "musl"
os = "linux"

    [[tblis.download]]
    sha256 = "c2905e233ba8277f2f948c81dbc4dd38722238b1e711a4241c13e1367908f1b5"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[tblis]]
arch = "x86_64"
git-tree-sha1 = "7ac08de524e60163faf378592bb75563870053ca"
os = "freebsd"

    [[tblis.download]]
    sha256 = "f2212d4b657bfc2bc46f671f28e379ff1f64876266c952864ee648e40e9f55d6"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e383ea743e3b9ad7757aded0cf71c7509c57897"
os = "windows"

    [[tblis.download]]
    sha256 = "4c376bbca58bc5daa9f65a35d29ccaa5f58388f3cdd61dcc87d12515b578e61b"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[tblis]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "805a9c1a8feac9ed36ed83beacbfbe6728c1982c"
os = "windows"

    [[tblis.download]]
    sha256 = "51cbc778d2c7c6ae55c9f4c9ec276414a042c2e122032263274da1c605d108b6"
    url = "https://github.com/JuliaBinaryWrappers/tblis_jll.jl/releases/download/tblis-v1.2.0+4/tblis.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
