# Autogenerated wrapper script for tblis_jll for x86_64-w64-mingw32-cxx03
export tblis, tci

using Hwloc_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("tblis")
JLLWrappers.@declare_library_product(tblis, "libtblis-0.dll")
JLLWrappers.@declare_library_product(tci, "libtci-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(Hwloc_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        tblis,
        "bin\\libtblis-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        tci,
        "bin\\libtci-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
