# Autogenerated wrapper script for tblis_jll for x86_64-unknown-freebsd
export tblis, tci

using Hwloc_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("tblis")
JLLWrappers.@declare_library_product(tblis, "libtblis.so.0")
JLLWrappers.@declare_library_product(tci, "libtci.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Hwloc_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        tblis,
        "lib/libtblis.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        tci,
        "lib/libtci.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
